import { SearchRouter } from './search/searchRouter.js';

export class ToolRegistry {
  public static getToolDefinitions() {
    return [
      {
        type: 'function' as const,
        function: {
          name: 'web_search',
          description:
            'Search the live internet for recent events, real-time facts, current news, documentation, or unknown information. Returns relevant excerpts and URLs.',
          parameters: {
            type: 'object',
            properties: {
              query: {
                type: 'string',
                description: 'The search query to look up on the web.',
              },
            },
            required: ['query'],
          },
        },
      },
    ];
  }

  public static async executeTool(name: string, args: Record<string, any>): Promise<any> {
    if (name === 'web_search') {
      const currentYear = new Date().getFullYear();
      let query = String(args.query || '').trim();

      // Normalize outdated years generated by model hallucinations (2024, 2025 -> currentYear)
      query = query.replace(/\b(2024|2025)\b/g, String(currentYear));

      console.log(`[SEARCH] Executing web_search for query: "${query}"`);
      const searchRouter = SearchRouter.getInstance();
      const results = await searchRouter.search(query, 5);
      return {
        query,
        resultsCount: results.length,
        results,
        formattedText: searchRouter.formatResults(results),
      };
    }

    return { error: `Tool "${name}" not found.` };
  }

  /**
   * Heuristic to proactively detect if a user message likely needs live web info,
   * especially beneficial for free models that don't always reliably output tool calling JSON.
   */
  public static shouldTriggerProactiveSearch(userText: string): string | null {
    const text = userText.toLowerCase();
    const currentYear = new Date().getFullYear();

    // Specific search trigger keywords
    const searchIntents = [
      /\b(tìm kiếm|tra cứu|search web|google|search for|lookup)\s+(.+)/i,
      /\b(tuần này|hôm nay|tháng này|năm nay|dạo này|gần đây|vừa qua)\b/i,
      /\b(tin tức|tin mới|tin nóng|xu hướng|trending|hot trend|sự kiện)\b/i,
      /\b(internet việt|mạng xã hội|báo chí|thời sự)\b/i,
      /\b(có gì mới|chuyện gì đang xảy ra|có gì hot)\b/i,
      /\b(thời tiết|giá vàng|tỉ giá|bitcoin|crypto price|chứng khoán)\b/i,
      /\b(who is the current|what happened today|latest news about|current price of)\s+(.+)/i,
      /\b(bây giờ là năm nào|năm nay là năm bao nhiêu|who won the|what is new in)\b/i,
    ];

    for (const regex of searchIntents) {
      const match = text.match(regex);
      if (match) {
        // Build a targeted search query
        let cleanText = userText.replace(/[?!,.]+/g, ' ').trim();
        // If query doesn't already contain a 4-digit year, append the current year
        if (!/\b\d{4}\b/.test(cleanText)) {
          cleanText = `${cleanText} ${currentYear}`;
        }
        return cleanText;
      }
    }

    return null;
  }
}
